fix: stream wasn't ever closed, gather never was called
agrarium/agrarium pull request #47
Opened 2019-01-30 08:42 UTC by werreour

2019-02-01 14:45 UTC, awinogradov approved these changes

2019-02-04 16:21 UTC, zxqfox commented on packages/core/src/index.ts
>              .all(plugins.map(p => p.seed && p.seed(chunk, context)))
Смысл seed в том, что их можно запускать параллельно, и здесь map ок (мб, конкурентности не хватает, разве что)

2019-02-04 16:22 UTC, zxqfox commented on packages/core/src/index.ts
> +                .all(plugins.map(f => f.gather && f.gather(chunk, context)));
Здесь .map нельзя, потому что gather нужно выполнять последовательно в том порядке, в котором отрабатывают плагины

2019-02-04 16:53 UTC, zxqfox commented on packages/core/src/index.ts
> +            this.push(chunk);
Точно не здесь лишний раз пушится chunk в поток?

2019-02-04 17:11 UTC, qfox requested changes

2019-02-04 17:11 UTC, zxqfox commented on packages/core/src/index.ts
> +                .all(plugins.map(f => f.gather && f.gather(chunk, context)));
Читаемо можно сделать как-то так, чтобы сохранить порядок (поток же у нас, всё-таки):
```js
    }, async function(
        this: Transform,
        next: Next<IChunk>,
    ) {
        for (const chunk of chunks) {
            try {
                chunk.data = Object.create(null);
                const res = await Promise
                    .all(plugins.map(f => f.gather && f.gather(chunk, context)));
                Object.assign.apply(null, ([] as Record<string, any>).concat(chunk.data, res));
                this.push(chunk);
            } catch (error) {
                next(error);
                break;
            }
        }
    }
```

2019-02-04 17:11 UTC, zxqfox commented on packages/core/src/index.ts
> +        Promise.all(promises).then(() => next()).catch(next);
Или здесь сделать конкурентно, если порядок не важен (кажется, что мы это обсуждали и решили, что не важен).
Bluebird.map с конкурентностью в 16 (highwatermark для objectMode потока).

2019-02-04 17:14 UTC, zxqfox commented on packages/core/src/index.ts
> +        Promise.all(promises).then(() => next()).catch(next);
Ток не забудь, что `const promises = chunks.map(async (chunk) => {` — на самом деле тут не промисы, а функции, которые еще надо запустить, чтобы получить промисы. Но для Bluebird.map как раз это и нужно, емнип

2019-02-05 14:43 UTC, werreour commented on packages/core/src/index.ts
> +        Promise.all(promises).then(() => next()).catch(next);
> самом деле тут не промисы

Вот это я не совсем понял:
```
const wait = time => new Promise(res => setTimeout(res, time));
const items = [1,2,3];
const promises = items.map(async (i) => {
	await wait(1000 * i);
	console.log(i)
});
Promise.all(promises).then(() => console.log('done'))
```
Будет же
```
1
2
3
done
```

2019-02-05 14:52 UTC, werreour commented on packages/core/src/index.ts
> +                .all(plugins.map(f => f.gather && f.gather(chunk, context)));
Относительно порядка не совсем понятно, как мы можем гарантировать порядок чтения с файловой системы?
Или речь про порядок плагинов? Тогда они и в этом случае не будут сохранять порядок (`reduce`)?

2019-02-06 17:25 UTC, zxqfox commented on packages/core/src/index.ts
> +        Promise.all(promises).then(() => next()).catch(next);
Перечитал кода к вечеру, мне, почему-то, видилось, что ты возвращаешь из map `async () => {}`
Всё норм

2019-02-06 17:33 UTC, zxqfox commented on packages/core/src/index.ts
> +                .all(plugins.map(f => f.gather && f.gather(chunk, context)));
ТрансформПотоки по умолчанию так устроены, что порядок на входе совпадает с порядком на выходе, обрабатываемый чанк только 1 (если специально не изобретать иного), и в буфере 16 объектов (т.е. если мы очень медленно обрабатываем в потоке — будет приостановлен и входной поток, чтобы не переливалось через край).
Из документации следует, что и seeds, и gather вызываются параллельно, я уже не помню почему в какой-то момент мы хотели gather последовательно, а потом отказались. Мне кажется, что это было связано с итоговым форматированием, но т.к. мы это вынесли из зоны действия плагинов — то и условие запускаться последовательно отвалилось. Я бы мб и вернул, на самом деле, но только в случае, если реально найдем смысл. Да и порядок не понятно кому нужен.

2019-02-06 17:33 UTC, qfox approved these changes

2019-02-07 12:16 UTC, werreour commented on packages/core/src/index.ts
> +                .all(plugins.map(f => f.gather && f.gather(chunk, context)));
А какая разница, мы же обрабатываем через `_flush` через `through2`, тут ограничения в 16 объектов не для нас (а для тех, кто будет после).

2019-02-07 12:17 UTC, werreour commented
@zxqfox @awinogradov 
А от меня еще что-то требуется в пулле?

2019-02-10 15:35 UTC, zxqfox commented
@awinogradov есть ощущение, что я из монорепы не релизил ни разу, можешь опубликовать или доступов выдать?

2019-02-12 15:30 UTC, merged